name: 'Publish files from /blog/**.md from last commit to Hashnode'
description:
  'Publish .md files from commit that triggered the action to Hashnode blog.'
author: 'Nicolas Guillen @nicolascalev'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'book-open'
  color: 'blue'

# Define your inputs here.
inputs:
  HASHNODE_HOST:
    description: 'Your blog host. Usually [username].hashnode.dev'
    required: true
  HASHNODE_PAT:
    description: 'Your Hashnode Personal Access Token from secrets'
    required: true

runs:
  using: node20
  main: dist/index.js
